import type { Metadata } from "next";

import './globals.css'
import ContextProvider from "@/context/ContextProvider";
import Navbar from "@/components/home/Navbar";
// import SocketComponent from "@/components/Socket";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      <html lang="en" suppressHydrationWarning>


        <ContextProvider>
          <body className="bg-gray-100 scroll-smooth">
            {/* <SocketComponent/> */}
            <Navbar/>
            <div className="min-h-screen flex flex-col">{children}</div>

          </body>
        </ContextProvider>
      </html>
    </>
  );
};
