# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Install required packages
RUN apk add --no-cache bash

# Install deps
COPY package.json package-lock.json ./
RUN npm install

# Copy source
COPY . .

# Install nodemon globally
RUN npm install -g nodemon ts-node typescript

# Expose your dev port
EXPOSE 3000

CMD ["nodemon", "--watch", ".", "--ext", "ts,tsx,js,json", "--exec", "ts-node", "server.ts"]
